#Spring App name
spring:
  application:
    name: BootIOCProj10-MiniProject-RealtimeDI
# Activate the profile
  #profiles:
    #active: prod
---
 # Define dev profile
spring: 
   config:
     activate:
       on-profile: dev
   datasource:
       driver-class-name: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql:///ntspbms717db
       username: root
       password: root
       type: org.apache.tomcat.jdbc.pool.DataSource
---
  # Define test profile
spring: 
   config:
      activate:
         on-profile: test
   datasource:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql:///ntspbms717db
            username: root
            password: root
            type: org.apache.tomcat.jdbc.pool.DataSource
---
 # Define test profile
spring: 
  config:
      activate:
       on-profile: uat
  datasource:
           driver-class-name: oracle.jdbc.driver.OracleDriver
           url: jdbc:oracle:thin:@localhost:1521:xe
           username: system
           password: tiger
           type: oracle.ucp.jdbc.PoolDataSourceImpl

---
    # Define prod profile
 spring: 
      config:
         activate:
           on-profile: prod
      datasource:
             driver-class-name: oracle.jdbc.driver.OracleDriver
             url: jdbc:oracle:thin:@localhost:1521:xe
             username: system
             password: tiger
